In [1]:
# Reading multiple data files:

#Tools for pandas data import
#● pd.read_csv() for CSV files
#● dataframe = pd.read_csv(filepath)
#● dozens of optional input parameters
#● Other data import tools:
#● pd.read_excel()
#● pd.read_html()
#● pd.read_json()   
    

In [ ]:
# Loading separate files:

import pandas as pd
dataframe0 = pd.read_csv('sales-jan-2015.csv')
dataframe1 = pd.read_csv('sales-feb-2015.csv')

In [ ]:
# Using a loop:

filenames = ['sales-jan-2015.csv', 'sales-feb-2015.csv']
dataframes = []
for f in filenames:
    dataframes.append(pd.read_csv(f))

In [ ]:
# Using a comprehension:

filenames = ['sales-jan-2015.csv', 'sales-feb-2015.csv']
dataframes = [pd.read_csv(f) for f in filenames]

In [ ]:
# Using glob:

from glob import glob
filenames = glob('sales*.csv')
dataframes = [pd.read_csv(f) for f in filenames]

In [4]:
# Reindexing DataFrames:

#“Indexes” vs. “Indices”:

#● indices: many index labels within Index data structures
#● indexes: many pandas Index data structures

import os

os.getcwd()

os.chdir('C:/Users/stayde/Documents/Python Scripts/Python_10_Files')

In [6]:
#Importing weather data

import pandas as pd
w_mean = pd.read_csv('quarterly_mean_temp.csv', index_col='Month')
w_max = pd.read_csv('quarterly_max_temp.csv', index_col='Month')

In [9]:
#Examining the data:

print(w_mean)

print(w_max)

       Mean TemperatureF
Month                   
Apr            61.956044
Jan            32.133333
July           68.934783
Oct            43.434783
       Max TemperatureF
Month                  
Jan                  68
Apr                  89
Jul                  91
Oct                  84


In [10]:
#The DataFrame indexes:

print(w_mean.index) 

Index(['Apr', 'Jan', 'July', 'Oct'], dtype='object', name='Month')


In [11]:
print(w_max.index)

Index(['Jan', 'Apr', 'Jul', 'Oct'], dtype='object', name='Month')


In [12]:
print(type(w_mean.index))

<class 'pandas.core.indexes.base.Index'>


In [18]:
# Using .reindex():

ordered = ['Jan', 'Apr', 'Jul', 'Oct']

w_mean2 = w_mean.reindex(ordered)

In [19]:
print(w_mean2)

       Mean TemperatureF
Month                   
Jan            32.133333
Apr            61.956044
Jul                  NaN
Oct            43.434783


In [30]:
# Using .sort_index():

w_mean2.sort_index()

Mean TemperatureF
Month                   
Apr            61.956044
Jan            32.133333
Jul                  NaN
Oct            43.434783

In [29]:
# Reindex from a DataFrame Index:

w_mean.reindex(w_max.index)


Mean TemperatureF
Month                   
Jan            32.133333
Apr            61.956044
Jul                  NaN
Oct            43.434783

In [28]:
# Reindexing with missing labels:

w_mean3 = w_mean.reindex(['Jan', 'Apr', 'Dec'])

w_mean3
    

Mean TemperatureF
Month                   
Jan            32.133333
Apr            61.956044
Dec                  NaN

In [27]:
# Reindex from a DataFrame Index :

w_max.reindex(w_mean3.index)

w_max.reindex(w_mean3.index).dropna()

Max TemperatureF
Month                  
Jan                68.0
Apr                89.0

In [26]:
#Order matters:

print(w_max.reindex(w_mean.index))

print(w_mean.reindex(w_max.index))

       Max TemperatureF
Month                  
Apr                89.0
Jan                68.0
July                NaN
Oct                84.0
       Mean TemperatureF
Month                   
Jan            32.133333
Apr            61.956044
Jul                  NaN
Oct            43.434783


In [33]:
# Arithmetic with Series & DataFrames:

#Loading weather data:

weather = pd.read_csv('pittsburgh2013.csv', index_col='Date', parse_dates=True)

weather.head()

Max TemperatureF  Mean TemperatureF  Min TemperatureF  \
Date                                                                
2013-01-01                32                 28                21   
2013-01-02                25                 21                17   
2013-01-03                32                 24                16   
2013-01-04                30                 28                27   
2013-01-05                34                 30                25   

            Max Dew PointF  Mean Dew PointF  Min DewpointF  Max Humidity  \
Date                                                                       
2013-01-01              30               27             16           100   
2013-01-02              14               12             10            77   
2013-01-03              19               15              9            77   
2013-01-04              21               19             17            75   
2013-01-05              23               20             16            75   

            Mean Humidity  Min Humidity  Max Sea Level PressureIn  ...  \
Date                                                               ...   
2013-01-01             89            77                     30.10  ...   
2013-01-02             67            55                     30.27  ...   
2013-01-03             67            56                     30.25  ...   
2013-01-04             68            59                     30.28  ...   
2013-01-05             68            61                     30.42  ...   

            Max VisibilityMiles  Mean VisibilityMiles  Min VisibilityMiles  \
Date                                                                         
2013-01-01                   10                     6                    2   
2013-01-02                   10                    10                   10   
2013-01-03                   10                    10                   10   
2013-01-04                   10                    10                    6   
2013-01-05                   10                    10                   10   

            Max Wind SpeedMPH  Mean Wind SpeedMPH  Max Gust SpeedMPH  \
Date                                                                   
2013-01-01                 10                   8                NaN   
2013-01-02                 14                   5                NaN   
2013-01-03                 17                   8               26.0   
2013-01-04                 23                  16               32.0   
2013-01-05                 16                  10               23.0   

            PrecipitationIn  CloudCover  Events  WindDirDegrees  
Date                                                             
2013-01-01             0.00           8    Snow             277  
2013-01-02             0.00           4     NaN             272  
2013-01-03             0.00           3     NaN             229  
2013-01-04             0.00           4     NaN             250  
2013-01-05             0.21           5     NaN             221  

[5 rows x 22 columns]

In [35]:
weather.loc['2013-7-1':'2013-7-7', 'PrecipitationIn']

Date
2013-07-01    0.18
2013-07-02    0.14
2013-07-03    0.00
2013-07-04    0.25
2013-07-05    0.02
2013-07-06    0.06
2013-07-07    0.10
Name: PrecipitationIn, dtype: float64

In [36]:
# Scalar multiplication:

weather.loc['2013-7-1':'2013-7-7', 'PrecipitationIn']*2.54

Date
2013-07-01    0.4572
2013-07-02    0.3556
2013-07-03    0.0000
2013-07-04    0.6350
2013-07-05    0.0508
2013-07-06    0.1524
2013-07-07    0.2540
Name: PrecipitationIn, dtype: float64

In [37]:
# Absolute temperature range:

week1_range = weather.loc['2013-07-01':'2013-07-07',['Min TemperatureF', 'Max TemperatureF']]

print(week1_range)

            Min TemperatureF  Max TemperatureF
Date                                          
2013-07-01                66                79
2013-07-02                66                84
2013-07-03                71                86
2013-07-04                70                86
2013-07-05                69                86
2013-07-06                70                89
2013-07-07                70                77


In [40]:
#Average temperature:

week1_mean = weather.loc['2013-07-01':'2013-07-07', 'Mean TemperatureF'] 

print(week1_mean)

Date
2013-07-01    72
2013-07-02    74
2013-07-03    78
2013-07-04    77
2013-07-05    76
2013-07-06    78
2013-07-07    72
Name: Mean TemperatureF, dtype: int64


In [44]:
#Relative temperature range:

(week1_range / week1_mean)

#So here in output we are getting NaN values


2013-07-01 00:00:00  2013-07-02 00:00:00  2013-07-03 00:00:00  \
Date                                                                        
2013-07-01                  NaN                  NaN                  NaN   
2013-07-02                  NaN                  NaN                  NaN   
2013-07-03                  NaN                  NaN                  NaN   
2013-07-04                  NaN                  NaN                  NaN   
2013-07-05                  NaN                  NaN                  NaN   
2013-07-06                  NaN                  NaN                  NaN   
2013-07-07                  NaN                  NaN                  NaN   

            2013-07-04 00:00:00  2013-07-05 00:00:00  2013-07-06 00:00:00  \
Date                                                                        
2013-07-01                  NaN                  NaN                  NaN   
2013-07-02                  NaN                  NaN                  NaN   
2013-07-03                  NaN                  NaN                  NaN   
2013-07-04                  NaN                  NaN                  NaN   
2013-07-05                  NaN                  NaN                  NaN   
2013-07-06                  NaN                  NaN                  NaN   
2013-07-07                  NaN                  NaN                  NaN   

            2013-07-07 00:00:00  Max TemperatureF  Min TemperatureF  
Date                                                                 
2013-07-01                  NaN               NaN               NaN  
2013-07-02                  NaN               NaN               NaN  
2013-07-03                  NaN               NaN               NaN  
2013-07-04                  NaN               NaN               NaN  
2013-07-05                  NaN               NaN               NaN  
2013-07-06                  NaN               NaN               NaN  
2013-07-07                  NaN               NaN               NaN

In [45]:
# Relative temperature range:

week1_range.divide(week1_mean, axis='rows')

Min TemperatureF  Max TemperatureF
Date                                          
2013-07-01          0.916667          1.097222
2013-07-02          0.891892          1.135135
2013-07-03          0.910256          1.102564
2013-07-04          0.909091          1.116883
2013-07-05          0.907895          1.131579
2013-07-06          0.897436          1.141026
2013-07-07          0.972222          1.069444

In [46]:
# Percentage changes:

week1_mean.pct_change() * 100

Date
2013-07-01         NaN
2013-07-02    2.777778
2013-07-03    5.405405
2013-07-04   -1.282051
2013-07-05   -1.298701
2013-07-06    2.631579
2013-07-07   -7.692308
Name: Mean TemperatureF, dtype: float64

In [58]:
# Bronze Olympic medals:

bronze = pd.read_csv('bronze_top5.csv', index_col=0)

print(bronze)

print(30*'*')

# Silver Olympic medals:

silver = pd.read_csv('silver_top5.csv', index_col=0)

print(silver)


# Gold Olympic medals:

gold = pd.read_csv('gold_top5.csv', index_col=0)

print(gold)


               Total
Country             
UnitedStates    1052
SovietUnion      584
UnitedKingdom    505
France           475
Germany          454
******************************
               Total
Country             
UnitedStates    1195
SovietUnion      627
UnitedKingdom    591
France           461
Italy            394
               Total
Country             
UnitedStates    2088
SovietUnion      838
UnitedKingdom    498
Italy            460
Germany          407


In [60]:
# Adding bronze, silver:

bronze + silver

Total
Country              
France          936.0
Germany           NaN
Italy             NaN
SovietUnion    1211.0
UnitedKingdom  1096.0
UnitedStates   2247.0

In [62]:
#Using the .add() method:

bronze.add(silver)

#So we are getting same putput as above. No difference

Total
Country              
France          936.0
Germany           NaN
Italy             NaN
SovietUnion    1211.0
UnitedKingdom  1096.0
UnitedStates   2247.0

In [64]:
# Using a fill_value:

bronze.add(silver, fill_value=0)

#So here we can get rid of NaN values. So .add function is useful.


Total
Country              
France          936.0
Germany         454.0
Italy           394.0
SovietUnion    1211.0
UnitedKingdom  1096.0
UnitedStates   2247.0

In [65]:
# Adding bronze, silver, gold:

bronze + silver + gold

Total
Country              
France            NaN
Germany           NaN
Italy             NaN
SovietUnion    2049.0
UnitedKingdom  1594.0
UnitedStates   4335.0

In [67]:
#Chaining .add():

bronze.add(silver, fill_value = 0).add(gold, fill_value = 0)


Total
Country              
France          936.0
Germany         861.0
Italy           854.0
SovietUnion    2049.0
UnitedKingdom  1594.0
UnitedStates   4335.0

In [ ]:
#Appending & concatenating Series:

#append()

#● .append(): Series & DataFrame method
#● Invocation:
#● s1.append(s2)
#● Stacks rows of s2 below s1
#● Method for Series & DataFrames


In [ ]:
#concat()

#● concat(): pandas module function
#● Invocation:
#● pd.concat([s1, s2, s3])
#● Can stack row-wise or column-wise


In [ ]:
# concat() & .append():

#● Equivalence of concat() & .append():
    #● result1 = pd.concat([s1, s2, s3])
    #● result2 = s1.append(s2).append(s3)
#● result1 == result2 elementwise

In [68]:
#Series of US states:

import pandas as pd

northeast = pd.Series(['CT', 'ME', 'MA', 'NH', 'RI', 'VT','NJ', 'NY', 'PA'])

south = pd.Series(['DE', 'FL', 'GA', 'MD', 'NC', 'SC', 'VA','DC', 'WV', 'AL', 'KY', 'MS', 'TN', 'AR', 'LA', 'OK', 'TX'])

midwest = pd.Series(['IL', 'IN', 'MN', 'MO', 'NE', 'ND','SD', 'IA', 'KS', 'MI', 'OH', 'WI'])

west = pd.Series(['AZ', 'CO', 'ID', 'MT', 'NV', 'NM','UT', 'WY', 'AK', 'CA', 'HI', 'OR','WA'])


In [70]:
#Using .append():

east = northeast.append(south)

east

0     CT
1     ME
2     MA
3     NH
4     RI
5     VT
6     NJ
7     NY
8     PA
0     DE
1     FL
2     GA
3     MD
4     NC
5     SC
6     VA
7     DC
8     WV
9     AL
10    KY
11    MS
12    TN
13    AR
14    LA
15    OK
16    TX
dtype: object

In [71]:
#But the problem with above indexing is, in middle also we are getting 0 index.

print(east.index)

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  0,  1,  2,  3,  4,  5,  6,  7,
             8,  9, 10, 11, 12, 13, 14, 15, 16],
           dtype='int64')


In [72]:
#So for following command we will get 2 outputs:

print(east.loc[3])

3    NH
3    MD
dtype: object


In [76]:
# Using .reset_index():

new_east = northeast.append(south).reset_index(drop = True)

print(new_east)

0     CT
1     ME
2     MA
3     NH
4     RI
5     VT
6     NJ
7     NY
8     PA
9     DE
10    FL
11    GA
12    MD
13    NC
14    SC
15    VA
16    DC
17    WV
18    AL
19    KY
20    MS
21    TN
22    AR
23    LA
24    OK
25    TX
dtype: object


In [77]:
print(new_east.index)

RangeIndex(start=0, stop=26, step=1)


In [85]:
# Using concat():

east = pd.concat([northeast, south])

print(east.head(12))

#Same output as of append

0    CT
1    ME
2    MA
3    NH
4    RI
5    VT
6    NJ
7    NY
8    PA
0    DE
1    FL
2    GA
dtype: object


In [83]:
print(east.index)

#Same output as of append

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  0,  1,  2,  3,  4,  5,  6,  7,
             8,  9, 10, 11, 12, 13, 14, 15, 16],
           dtype='int64')


In [86]:
#Using ignore_index:

new_east = pd.concat([northeast, south], ignore_index = True)

In [87]:
print(new_east.head(11))

0     CT
1     ME
2     MA
3     NH
4     RI
5     VT
6     NJ
7     NY
8     PA
9     DE
10    FL
dtype: object


In [89]:
print(new_east.index)

RangeIndex(start=0, stop=26, step=1)


In [90]:
# Appending & concatenating DataFrames:

# Loading population data:

import pandas as pd
pop1 = pd.read_csv('population_01.csv', index_col=0)
pop2 = pd.read_csv('population_02.csv', index_col=0)

print(type(pop1), pop1.shape)

print(type(pop2), pop2.shape)


<class 'pandas.core.frame.DataFrame'> (4, 1)
<class 'pandas.core.frame.DataFrame'> (4, 1)


In [93]:
# Examining population data:

print(pop1)

print(40*'*')

print(pop2)

               2010 Census Population
Zip Code ZCTA                        
66407                             479
72732                            4716
50579                            2405
46241                           30670
****************************************
               2010 Census Population
Zip Code ZCTA                        
12776                            2180
76092                           26669
98360                           12221
49464                           27481


In [94]:
# Appending population DataFrames:

pop1.append(pop2)

2010 Census Population
Zip Code ZCTA                        
66407                             479
72732                            4716
50579                            2405
46241                           30670
12776                            2180
76092                           26669
98360                           12221
49464                           27481

In [96]:
print(pop1.index.name, pop1.columns)

print(pop2.index.name, pop2.columns) 

Zip Code ZCTA Index(['2010 Census Population'], dtype='object')
Zip Code ZCTA Index(['2010 Census Population'], dtype='object')


In [99]:
# Population & unemployment data:

population = pd.read_csv('population_00.csv', index_col=0)

unemployment = pd.read_csv('unemployment_00.csv', index_col=0)

print(population)

print(unemployment)

               2010 Census Population
Zip Code ZCTA                        
57538                             322
59916                             130
37660                           40038
2860                            45199
       unemployment  participants 
Zip                               
2860           0.11          34447
46167          0.02           4800
1097           0.33             42
80808          0.07           4310


In [101]:
# Appending population & unemployment:

population.append(unemployment)

# In below output, we can see Repeated index labels (for 2860)

2010 Census Population  participants   unemployment
57538                   322.0            NaN           NaN
59916                   130.0            NaN           NaN
37660                 40038.0            NaN           NaN
2860                  45199.0            NaN           NaN
2860                      NaN        34447.0          0.11
46167                     NaN         4800.0          0.02
1097                      NaN           42.0          0.33
80808                     NaN         4310.0          0.07

In [105]:
# Concatenating rows:

pd.concat([population, unemployment], axis=0)

C:\Users\stayde\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


2010 Census Population  participants   unemployment
57538                   322.0            NaN           NaN
59916                   130.0            NaN           NaN
37660                 40038.0            NaN           NaN
2860                  45199.0            NaN           NaN
2860                      NaN        34447.0          0.11
46167                     NaN         4800.0          0.02
1097                      NaN           42.0          0.33
80808                     NaN         4310.0          0.07

In [107]:
# Concatenating columns:

pd.concat([population, unemployment], axis=1) 

2010 Census Population  unemployment  participants 
1097                      NaN          0.33           42.0
2860                  45199.0          0.11        34447.0
37660                 40038.0           NaN            NaN
46167                     NaN          0.02         4800.0
57538                   322.0           NaN            NaN
59916                   130.0           NaN            NaN
80808                     NaN          0.07         4310.0

In [108]:
# Concatenation, keys, & MultiIndexes:

#Loading rainfall data:

import pandas as pd
file1 = 'q1_rainfall_2013.csv'

rain2013 = pd.read_csv(file1, index_col='Month', parse_dates=True)

file2 = 'q1_rainfall_2014.csv'
rain2014 = pd.read_csv(file2, index_col='Month', parse_dates=True)

In [111]:
print(rain2013)
print(30*'*')
print(rain2014)

       Precipitation
Month               
Jan         0.096129
Feb         0.067143
Mar         0.061613
******************************
       Precipitation
Month               
Jan         0.050323
Feb         0.082143
Mar         0.070968


In [113]:
# Concatenating rows:

pd.concat([rain2013, rain2014], axis=0)

Precipitation
Month               
Jan         0.096129
Feb         0.067143
Mar         0.061613
Jan         0.050323
Feb         0.082143
Mar         0.070968

In [116]:
# Using multi-index on rows:

rain1314 = pd.concat([rain2013, rain2014], keys=[2013, 2014], axis=0)
print(rain1314)

            Precipitation
     Month               
2013 Jan         0.096129
     Feb         0.067143
     Mar         0.061613
2014 Jan         0.050323
     Feb         0.082143
     Mar         0.070968


In [117]:
# Accessing a multi-index:

print(rain1314.loc[2014])

       Precipitation
Month               
Jan         0.050323
Feb         0.082143
Mar         0.070968


In [122]:
# Concatenating columns:

rain1314 = pd.concat([rain2013, rain2014], axis='columns')

print(rain1314)

       Precipitation  Precipitation
Month                              
Jan         0.096129       0.050323
Feb         0.067143       0.082143
Mar         0.061613       0.070968


In [127]:
# Using a multi-index on columns:

rain1314 = pd.concat([rain2013, rain2014], keys=[2013, 2014], axis='columns')

print(rain1314)

               2013          2014
      Precipitation Precipitation
Month                            
Jan        0.096129      0.050323
Feb        0.067143      0.082143
Mar        0.061613      0.070968


In [125]:
#We can also access the data as required:

rain1314[2013]

Precipitation
Month               
Jan         0.096129
Feb         0.067143
Mar         0.061613

In [131]:
# pd.concat() with dict:

rain_dict = {2013: rain2013, 2014: rain2014} 

rain1314 = pd.concat(rain_dict, axis='columns')

print(rain1314)

               2013          2014
      Precipitation Precipitation
Month                            
Jan        0.096129      0.050323
Feb        0.067143      0.082143
Mar        0.061613      0.070968


In [134]:
# Outer & inner joins:

# Using with arrays:

import numpy as np
import pandas as pd

A = np.arange(8).reshape(2,4) + 0.1

print(A)
print(20*'*')

B = np.arange(6).reshape(2,3) + 0.2

print(B)
print(20*'*')

C = np.arange(12).reshape(3,4) + 0.3

print(C)


[[0.1 1.1 2.1 3.1]
 [4.1 5.1 6.1 7.1]]
********************
[[0.2 1.2 2.2]
 [3.2 4.2 5.2]]
********************
[[ 0.3  1.3  2.3  3.3]
 [ 4.3  5.3  6.3  7.3]
 [ 8.3  9.3 10.3 11.3]]


In [135]:
# Stacking arrays horizontally (Columnwise Operation):

np.hstack([B,A])

np.concatenate([B,A], axis = 1)

array([[0.2, 1.2, 2.2, 0.1, 1.1, 2.1, 3.1],
       [3.2, 4.2, 5.2, 4.1, 5.1, 6.1, 7.1]])

In [136]:
# Stacking arrays vertically (row-wise):

np.vstack([A, C]) 

np.concatenate([A, C], axis=0)

array([[ 0.1,  1.1,  2.1,  3.1],
       [ 4.1,  5.1,  6.1,  7.1],
       [ 0.3,  1.3,  2.3,  3.3],
       [ 4.3,  5.3,  6.3,  7.3],
       [ 8.3,  9.3, 10.3, 11.3]])

In [ ]:
# Incompatible array dimensions:

np.concatenate([A, B], axis=0)   #  incompatible columns 

np.concatenate([A, C], axis=1)   #  incompatible rows


In [137]:
# Population & unemployment data:

population = pd.read_csv('population_00.csv', index_col=0)

unemployment = pd.read_csv('unemployment_00.csv', index_col=0) 


In [138]:
print(population)

               2010 Census Population
Zip Code ZCTA                        
57538                             322
59916                             130
37660                           40038
2860                            45199


In [139]:
print(unemployment)

       unemployment  participants 
Zip                               
2860           0.11          34447
46167          0.02           4800
1097           0.33             42
80808          0.07           4310


In [142]:
#Converting to arrays:

population_array = np.array(population) 

unemployment_array = np.array(unemployment)

In [143]:
print(population_array)

[[  322]
 [  130]
 [40038]
 [45199]]


In [144]:
print(unemployment_array)

[[1.1000e-01 3.4447e+04]
 [2.0000e-02 4.8000e+03]
 [3.3000e-01 4.2000e+01]
 [7.0000e-02 4.3100e+03]]


In [145]:
# Manipulating data as arrays:

print(np.concatenate([population_array, unemployment_array], axis=1))


[[3.2200e+02 1.1000e-01 3.4447e+04]
 [1.3000e+02 2.0000e-02 4.8000e+03]
 [4.0038e+04 3.3000e-01 4.2000e+01]
 [4.5199e+04 7.0000e-02 4.3100e+03]]


In [146]:
# Joins
#● Joining tables: Combining rows of multiple tables
#● Outer join
    #● Union of index sets (all labels, no repetition)
    #● Missing fields filled with NaN
#● Inner join
#● Intersection of index sets (only common labels)

In [147]:
# Concatenation & inner join:

pd.concat([population, unemployment], axis=1, join='inner')

2010 Census Population  unemployment  participants 
2860                   45199          0.11          34447

In [148]:
# Concatenation & outer join:

pd.concat([population, unemployment], axis=1, join='outer')

2010 Census Population  unemployment  participants 
1097                      NaN          0.33           42.0
2860                  45199.0          0.11        34447.0
37660                 40038.0           NaN            NaN
46167                     NaN          0.02         4800.0
57538                   322.0           NaN            NaN
59916                   130.0           NaN            NaN
80808                     NaN          0.07         4310.0

In [150]:
# Inner join on other axis:

pd.concat([population, unemployment], join='inner', axis=0)

Empty DataFrame
Columns: []
Index: [57538, 59916, 37660, 2860, 2860, 46167, 1097, 80808]

In [5]:
# Merging DataFrames:

# Population DataFrame:

import pandas as pd

population = pd.read_csv('pa_zipcode_population.csv')

print(population)

   Zipcode  2010 Census Population
0    16855                     282
1    15681                    5241
2    18657                   11985
3    17307                    5899
4    15635                     220


In [7]:
cities = pd.read_csv('pa_zipcode_city.csv')

print(cities)

    Zipcode            City State
0     17545         MANHEIM    PA
1     18455     PRESTONPARK    PA
2     17307     BIGLERVILLE    PA
3     15705         INDIANA    PA
4     16833    CURWENSVILLE    PA
5     16220           CROWN    PA
6     18618     HARVEYSLAKE    PA
7     16855  MINERALSPRINGS    PA
8     16623       CASSVILLE    PA
9     15635      HANNASTOWN    PA
10    15681       SALTSBURG    PA
11    18657     TUNKHANNOCK    PA
12    15279      PITTSBURGH    PA
13    17231       LEMASTERS    PA
14    18821       GREATBEND    PA


In [8]:
# Merging:

pd.merge(population, cities)

Zipcode  2010 Census Population            City State
0    16855                     282  MINERALSPRINGS    PA
1    15681                    5241       SALTSBURG    PA
2    18657                   11985     TUNKHANNOCK    PA
3    17307                    5899     BIGLERVILLE    PA
4    15635                     220      HANNASTOWN    PA

In [9]:
bronze = pd.read_csv('bronze_sorted.csv')
gold = pd.read_csv('gold_sorted.csv') 

In [11]:
print(bronze)
print(30*'*')
print(gold)

   NOC        Country  Total
0  USA   UnitedStates   1052
1  URS    SovietUnion    584
2  GBR  UnitedKingdom    505
3  FRA         France    475
4  GER        Germany    454
******************************
   NOC        Country  Total
0  USA   UnitedStates   2088
1  URS    SovietUnion    838
2  GBR  UnitedKingdom    498
3  ITA          Italy    460
4  GER        Germany    407


In [12]:
pd.merge(bronze, gold)

Empty DataFrame
Columns: [NOC, Country, Total]
Index: []

In [14]:
# Merging on:

pd.merge(bronze, gold, on='NOC')

NOC      Country_x  Total_x      Country_y  Total_y
0  USA   UnitedStates     1052   UnitedStates     2088
1  URS    SovietUnion      584    SovietUnion      838
2  GBR  UnitedKingdom      505  UnitedKingdom      498
3  GER        Germany      454        Germany      407

In [15]:
# Merging on multiple columns:

pd.merge(bronze, gold, on=['NOC', 'Country'])

NOC        Country  Total_x  Total_y
0  USA   UnitedStates     1052     2088
1  URS    SovietUnion      584      838
2  GBR  UnitedKingdom      505      498
3  GER        Germany      454      407

In [18]:
# Using suffixes:

pd.merge(bronze, gold, on = 'NOC', suffixes = ['_Bronze', '_Gold'])

NOC Country_Bronze  Total_Bronze   Country_Gold  Total_Gold
0  USA   UnitedStates          1052   UnitedStates        2088
1  URS    SovietUnion           584    SovietUnion         838
2  GBR  UnitedKingdom           505  UnitedKingdom         498
3  GER        Germany           454        Germany         407

In [19]:
#Using Suffixes:

pd.merge(bronze, gold, on=['NOC', 'Country'], suffixes=['_bronze', '_gold']) 

NOC        Country  Total_bronze  Total_gold
0  USA   UnitedStates          1052        2088
1  URS    SovietUnion           584         838
2  GBR  UnitedKingdom           505         498
3  GER        Germany           454         407

In [25]:
# Counties DataFrame:

counties = pd.read_csv('pa_counties.csv')

print(counties)

print(40*'*')

print(cities.tail())

        CITY NAME   COUNTY NAME
0       SALTSBURG       INDIANA
1  MINERALSPRINGS    CLEARFIELD
2     BIGLERVILLE         ADAMS
3      HANNASTOWN  WESTMORELAND
4     TUNKHANNOCK       WYOMING
****************************************
    Zipcode         City State
10    15681    SALTSBURG    PA
11    18657  TUNKHANNOCK    PA
12    15279   PITTSBURGH    PA
13    17231    LEMASTERS    PA
14    18821    GREATBEND    PA


In [33]:
# Specifying columns to merge:

pd.merge(counties, cities, left_on = 'CITY NAME', right_on = 'City')

CITY NAME   COUNTY NAME  Zipcode            City State
0       SALTSBURG       INDIANA    15681       SALTSBURG    PA
1  MINERALSPRINGS    CLEARFIELD    16855  MINERALSPRINGS    PA
2     BIGLERVILLE         ADAMS    17307     BIGLERVILLE    PA
3      HANNASTOWN  WESTMORELAND    15635      HANNASTOWN    PA
4     TUNKHANNOCK       WYOMING    18657     TUNKHANNOCK    PA

In [35]:
# Switching left/right DataFrames:

pd.merge(cities, counties, left_on='City', right_on='CITY NAME')

Zipcode            City State       CITY NAME   COUNTY NAME
0    17307     BIGLERVILLE    PA     BIGLERVILLE         ADAMS
1    16855  MINERALSPRINGS    PA  MINERALSPRINGS    CLEARFIELD
2    15635      HANNASTOWN    PA      HANNASTOWN  WESTMORELAND
3    15681       SALTSBURG    PA       SALTSBURG       INDIANA
4    18657     TUNKHANNOCK    PA     TUNKHANNOCK       WYOMING

In [36]:
# Joining DataFrames:

# Medal DataFrames:

import pandas as pd
bronze = pd.read_csv('bronze_sorted.csv')
gold = pd.read_csv('gold_sorted.csv')

In [40]:
print(gold)
print(30*'*')
print(bronze)

   NOC        Country  Total
0  USA   UnitedStates   2088
1  URS    SovietUnion    838
2  GBR  UnitedKingdom    498
3  ITA          Italy    460
4  GER        Germany    407
******************************
   NOC        Country  Total
0  USA   UnitedStates   1052
1  URS    SovietUnion    584
2  GBR  UnitedKingdom    505
3  FRA         France    475
4  GER        Germany    454


In [41]:
# Merging with inner join:

pd.merge(bronze, gold, on=['NOC', 'Country'], suffixes=['_bronze', '_gold'], how='inner') 

NOC        Country  Total_bronze  Total_gold
0  USA   UnitedStates          1052        2088
1  URS    SovietUnion           584         838
2  GBR  UnitedKingdom           505         498
3  GER        Germany           454         407

In [ ]:
# Merging with left join:

#● Keeps all rows of the le! DF in the merged DF
#● For rows in the le! DF with matches in the right DF:
    #● Non-joining columns of right DF are appended to le! DF
#● For rows in the le! DF with no matches in the right DF:
    #● Non-joining columns are filled with nulls
    


In [43]:
# Merging with left join:

pd.merge(bronze, gold, on=['NOC', 'Country'], suffixes=['_bronze', '_gold'], how = 'left') 

NOC        Country  Total_bronze  Total_gold
0  USA   UnitedStates          1052      2088.0
1  URS    SovietUnion           584       838.0
2  GBR  UnitedKingdom           505       498.0
3  FRA         France           475         NaN
4  GER        Germany           454       407.0

In [45]:
# Merging with right join:

pd.merge(bronze, gold, on=['NOC', 'Country'], suffixes=['_bronze', '_gold'], how = 'right') 

NOC        Country  Total_bronze  Total_gold
0  USA   UnitedStates        1052.0        2088
1  URS    SovietUnion         584.0         838
2  GBR  UnitedKingdom         505.0         498
3  GER        Germany         454.0         407
4  ITA          Italy           NaN         460

In [46]:
# Merging with outer join:

pd.merge(bronze, gold, on=['NOC', 'Country'], suffixes=['_bronze', '_gold'], how = 'outer') 

NOC        Country  Total_bronze  Total_gold
0  USA   UnitedStates        1052.0      2088.0
1  URS    SovietUnion         584.0       838.0
2  GBR  UnitedKingdom         505.0       498.0
3  FRA         France         475.0         NaN
4  GER        Germany         454.0       407.0
5  ITA          Italy           NaN       460.0

In [47]:
# Population & unemployment data:

population = pd.read_csv('population_00.csv', index_col=0)
unemployment = pd.read_csv('unemployment_00.csv', index_col=0)

In [49]:
print(population)

print(40*'*')

print(unemployment)

               2010 Census Population
Zip Code ZCTA                        
57538                             322
59916                             130
37660                           40038
2860                            45199
****************************************
       unemployment  participants 
Zip                               
2860           0.11          34447
46167          0.02           4800
1097           0.33             42
80808          0.07           4310


In [50]:
# Using .join(how=‘left’):

population.join(unemployment, how = 'left')

2010 Census Population  unemployment  participants 
Zip Code ZCTA                                                     
57538                             322           NaN            NaN
59916                             130           NaN            NaN
37660                           40038           NaN            NaN
2860                            45199          0.11        34447.0

In [51]:
# Using .join(how=‘right’):

population.join(unemployment, how = 'right')

2010 Census Population  unemployment  participants 
Zip                                                       
2860                  45199.0          0.11          34447
46167                     NaN          0.02           4800
1097                      NaN          0.33             42
80808                     NaN          0.07           4310

In [52]:
#Using .join(how=‘inner’):

population.join(unemployment, how = 'inner')

2010 Census Population  unemployment  participants 
2860                   45199          0.11          34447

In [53]:
#Using .join(how=‘outer’):

population.join(unemployment, how = 'outer')

2010 Census Population  unemployment  participants 
1097                      NaN          0.33           42.0
2860                  45199.0          0.11        34447.0
37660                 40038.0           NaN            NaN
46167                     NaN          0.02         4800.0
57538                   322.0           NaN            NaN
59916                   130.0           NaN            NaN
80808                     NaN          0.07         4310.0

In [60]:
#Which should you use?
#● df1.append(df2): stacking vertically
#● pd.concat([df1, df2]):
    #● stacking many horizontally or vertically
    #● simple inner/outer joins on Indexes
#● df1.join(df2): inner/outer/le!/right joins on Indexes
#● pd.merge([df1, df2]): many joins on multiple columns

print(population.head(3))
print(unemployment.head(3))

               2010 Census Population
Zip Code ZCTA                        
57538                             322
59916                             130
37660                           40038
       unemployment  participants 
Zip                               
2860           0.11          34447
46167          0.02           4800
1097           0.33             42


In [66]:
#Ordered merges:

#Software & hardware sales:

software = pd.read_csv('feb-sales-Software.csv', parse_dates =['Date']).sort_values('Date')

hardware = pd.read_csv('feb-sales-Hardware.csv', parse_dates=['Date']).sort_values('Date')


In [67]:
print(software)

print(60*'*')

print(hardware)

                 Date          Company   Product  Units
2 2015-02-02 08:33:00            Hooli  Software      3
1 2015-02-03 14:14:00          Initech  Software     13
7 2015-02-04 15:36:00        Streeplex  Software     13
3 2015-02-05 01:53:00  Acme Coporation  Software     19
5 2015-02-09 13:09:00        Mediacore  Software      7
4 2015-02-11 20:03:00          Initech  Software      7
6 2015-02-11 22:50:00            Hooli  Software      4
0 2015-02-16 12:09:00            Hooli  Software     10
8 2015-02-21 05:01:00        Mediacore  Software      3
************************************************************
                 Date          Company   Product  Units
3 2015-02-02 20:54:00        Mediacore  Hardware      9
0 2015-02-04 21:52:00  Acme Coporation  Hardware     14
1 2015-02-07 22:58:00  Acme Coporation  Hardware      1
2 2015-02-19 10:59:00        Mediacore  Hardware     16
4 2015-02-21 20:41:00            Hooli  Hardware      3


In [68]:
# Using merge():

pd.merge(software, hardware)

Empty DataFrame
Columns: [Date, Company, Product, Units]
Index: []

In [71]:
# Using merge(how=‘outer’):

pd.merge(hardware, software, how='outer')

Date          Company   Product  Units
0  2015-02-02 20:54:00        Mediacore  Hardware      9
1  2015-02-04 21:52:00  Acme Coporation  Hardware     14
2  2015-02-07 22:58:00  Acme Coporation  Hardware      1
3  2015-02-19 10:59:00        Mediacore  Hardware     16
4  2015-02-21 20:41:00            Hooli  Hardware      3
5  2015-02-02 08:33:00            Hooli  Software      3
6  2015-02-03 14:14:00          Initech  Software     13
7  2015-02-04 15:36:00        Streeplex  Software     13
8  2015-02-05 01:53:00  Acme Coporation  Software     19
9  2015-02-09 13:09:00        Mediacore  Software      7
10 2015-02-11 20:03:00          Initech  Software      7
11 2015-02-11 22:50:00            Hooli  Software      4
12 2015-02-16 12:09:00            Hooli  Software     10
13 2015-02-21 05:01:00        Mediacore  Software      3

In [80]:
#Using merge_ordered():

pd.merge_ordered(hardware, software)

Date          Company   Product  Units
0  2015-02-02 08:33:00            Hooli  Software      3
1  2015-02-02 20:54:00        Mediacore  Hardware      9
2  2015-02-03 14:14:00          Initech  Software     13
3  2015-02-04 15:36:00        Streeplex  Software     13
4  2015-02-04 21:52:00  Acme Coporation  Hardware     14
5  2015-02-05 01:53:00  Acme Coporation  Software     19
6  2015-02-07 22:58:00  Acme Coporation  Hardware      1
7  2015-02-09 13:09:00        Mediacore  Software      7
8  2015-02-11 20:03:00          Initech  Software      7
9  2015-02-11 22:50:00            Hooli  Software      4
10 2015-02-16 12:09:00            Hooli  Software     10
11 2015-02-19 10:59:00        Mediacore  Hardware     16
12 2015-02-21 05:01:00        Mediacore  Software      3
13 2015-02-21 20:41:00            Hooli  Hardware      3

In [81]:
#Using on & suffixes:

pd.merge_ordered(hardware, software, on=['Date', 'Company'],suffixes=['_hardware', '_software']).head()

Date          Company Product_hardware  Units_hardware  \
0 2015-02-02 08:33:00            Hooli              NaN             NaN   
1 2015-02-02 20:54:00        Mediacore         Hardware             9.0   
2 2015-02-03 14:14:00          Initech              NaN             NaN   
3 2015-02-04 15:36:00        Streeplex              NaN             NaN   
4 2015-02-04 21:52:00  Acme Coporation         Hardware            14.0   

  Product_software  Units_software  
0         Software             3.0  
1              NaN             NaN  
2         Software            13.0  
3         Software            13.0  
4              NaN             NaN